### ISSUE TITLE
Critical redundancy in code in index.js

### ISSUE THREAD

**Issue by SergPro** [spugachev/random-sort#1]
commented out debug code in index.js , line 9 - code style violation

https://github.com/spugachev/random-sort/blob/26ecbf5bb0e455692fc2697704e7a60f71241388/index.js#L9

**Comment by zkardava** [comment]
Fixed in 07753ecce3eb97180887ded60857f7ca13d8d103

**Comment by zkardava** [comment]
Closing issue.

**Comment by SergPro** [comment]
This commit 
https://github.com/spugachev/random-sort/commit/07753ecce3eb97180887ded60857f7ca13d8d103 solves several unrelated problems, which makes it difficult to follow
